language: java
jdk:
  - oraclejdk8
  
script: 
 mvn package
  
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  
addons:
  apt:
    packages:
      - oracle-java8-installer
